name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Give execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Find and upload APK
        uses: actions/upload-artifact@v4
        with:
          name: manager
          path: ./**/build/outputs/apk/debug/*.apk
          retention-days: 7

  release:
    needs:
      - build-manager
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Rename ksud
        run: |
          mkdir -p ksud
          for dir in ./ksud-*; do
              if [ -d "$dir" ]; then
                 echo "----- Rename $dir -----"
                 ksud_platform_name=$(basename "$dir")
                 find "$dir" -type f -name "ksud" -path "*/release/*" | while read -r ksud_file; do
                   if [ -f "$ksud_file" ]; then
                     mv "$ksud_file" "ksud/$ksud_platform_name"
                   fi
                 done
              fi
          done

      - name: Display structure of downloaded files
        run: ls -R

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manager/*.apk
            android*-lkm/*_kernelsu.ko
            ksud/ksud-*
            ksuinit/**
